In [67]:
import os
import numpy as np
from pathlib import Path
import pandas as pd

import pickle

In [15]:
NGAsub_folder = Path(r"C:\Users\clemettn\Desktop\02_NGASub")
RSNs_2_download = sorted([str(int(i)) for i in np.loadtxt(r"c:\Users\clemettn\Desktop\all_ngasub_records_to_download.csv", skiprows=1, delimiter=",")[:,0]])

RSN_folders = [f for f in os.listdir(NGAsub_folder) if "NGASub_RSN_" in f] 
downloaded_RSNs = [f.split("_")[-1] for f in RSN_folders]

In [18]:
not_downloaded = [rsn for rsn in RSNs_2_download if rsn not in downloaded_RSNs]
print(len(not_downloaded))

1217

checking the gcim distributions between the old and the new selection

In [34]:
old_selection_fp = Path(r"C:\Users\clemettn\Desktop\old_selection")
new_selection_fp = Path(r"C:\Users\clemettn\Desktop\new_selection")

with open(old_selection_fp / "05_gcim_distributions/gcim_dist_AvgSA_03.pickle", "rb") as file:
    old_gcim_dists = pickle.load(file)

with open(new_selection_fp / "05_gcim_distributions/gcim_dist_AvgSA_03.pickle", "rb") as file:
    new_gcim_dists = pickle.load(file)

In [63]:
key_1 = (4, np.float64(0.004988))

different_gcims = []
for k in old_gcim_dists.keys():
    if not all(old_gcim_dists[k]["stats"] == new_gcim_dists[k]["stats"]):
        different_gcims.append(k)

different_gcims

[]

this was a fuckup from me. I forgot to delete the old disaggregation files. But that means I would expect the selection to be exactly the same then...

checking the different stages of the record selection

In [72]:
with open(old_selection_fp / "06_gm_selection/AvgSA_03_prelim_selection.pickle", "rb") as file:
    old_prelim_03 = pickle.load(file)

with open(new_selection_fp / "06_gm_selection/AvgSA_03_prelim_selection.pickle", "rb") as file:
    new_prelim_03 = pickle.load(file)

with open(old_selection_fp / "06_gm_selection/AvgSA_06_prelim_selection.pickle", "rb") as file:
    old_prelim_06 = pickle.load(file)

with open(new_selection_fp / "06_gm_selection/AvgSA_06_prelim_selection.pickle", "rb") as file:
    new_prelim_06 = pickle.load(file)

In [58]:
old_prelim_03[key_1].keys()

dict_keys(['sims', 'mu_cond_sims', 'sig_cond_sims', 'ctxs', 'eps', 'recs', 'ks_passed', 'ks_results', 'ks_failed_ims', 'ks_bounds', 'R-score', 'ecdfs', 'quantiles', 'cond_imt', 'cond_iml', 'filter_stats'])

In [45]:
all(old_prelim_03[key_1]["sims"] == new_prelim_03[key_1]["sims"])

False

In [55]:
all(old_prelim_03[key_1]["recs"].index == new_prelim_03[key_1]["recs"].index)

False

In [59]:
old_prelim_03[key_1]["recs"].index

Index([  7657,  12304,   7303,  18932,   8540,  28188,  10218,  31276,  18953,
        31150,  12297,  12737,  33180,   8572,  19571,  31108,   7584,  19229,
        20989,  34787,  41401,  13818,  19985,   9482,  33888,  32137, 120592,
       117202, 114448, 108015],
      dtype='int64')

In [64]:
old_prelim_03[key_1]["recs"]

      metadata                                                       \
         index database               event_id           event_time
14086    15878      ESM           IT-2009-0121  2009-04-09 00:52:59
28372     8491      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
34129    14951      ESM           IT-2002-0045  2002-10-31 10:33:00
41077    21995      ESM           TK-1999-0077  1999-08-17 00:01:38
35080    15908      ESM           IT-2009-0121  2009-04-09 00:52:59
13587    15376      ESM           IT-2008-0004  2008-12-23 15:24:21
30415    10607      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
18373    20201      ESM           IT-2012-0061  2012-10-25 23:05:24
20168    22049      ESM           TK-1999-0294  1999-09-13 11:55:27
16167    17973      ESM           IT-2012-0008  2012-05-20 02:03:50
31188    11393      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
20226    22108      ESM           TK-1999-0415  1999-11-12 16:57:19
28241     8358      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
30388    10580      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
5649      6203      ESM  EMSC-20150417_0000011  2015-04-17 02:05:39
28294     8413      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
6553      7379      ESM  EMSC-20151117_0000032  2015-11-17 08:33:43
30381    10573      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
9296     10452      ESM  EMSC-20161026_0000077  2016-10-26 17:10:36
41517    22440      ESM           TK-2005-0036  2005-03-23 21:44:52
9500     10657      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
12648    14427      ESM           IT-1980-0012  1980-11-23 18:34:53
39959    20827      ESM           IT-2013-0005  2013-06-21 10:33:56
9354     10510      ESM  EMSC-20161026_0000077  2016-10-26 17:10:36
19610    21474      ESM           IT-2013-0019  2013-12-29 17:08:43
7367      8450      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
31233    11441      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
21937     1087      ESM  EMSC-20120304_0000006  2012-03-04 03:31:09
16183    17989      ESM           IT-2012-0008  2012-05-20 02:03:50
14018    15810      ESM           IT-2009-0102  2009-04-07 17:47:37

                                                                              \
      station_code location_code              trt   mag     rjb         vs30
14086         MI02             0  Shallow Default  5.43   18.10   445.161197
28372         RNI2             0  Shallow Default  6.00  126.00   911.178534
34129          SCV             0  Shallow Default  5.71   41.49   495.270730
41077          ZYT             0  Shallow Default  7.40   64.68   543.605561
35080          SCP             0  Shallow Default  5.43  168.00   627.932386
13587        MFSFB             0  Shallow Default  5.46  245.89  1191.010983
30415          CTD             0  Shallow Default  5.90   52.29   407.000000
18373          VNN             0  Shallow Default  5.30   49.20   659.540631
20168         5902             0  Shallow Default  5.82  212.69   408.000000
16167          FIE             0  Shallow Default  6.10  109.81   765.918906
31188          SDM             0  Shallow Default  6.50   54.23   752.000000
20226          MSK             0  Shallow Default  7.10  160.12   573.862512
28241          GSA             0  Shallow Default  6.00   30.74   492.000000
30388          AQG             0  Shallow Default  5.90   54.37   696.000000
5649           ZKR             0  Shallow Default  5.20   46.90   705.516993
28294          SSO             0  Shallow Default  6.00  111.61   538.428785
6553           KBN             0  Shallow Default  5.10  219.90   742.000000
30381          ACC             0  Shallow Default  5.90   18.05   833.346095
9296           NOR             0  Shallow Default  5.40   10.20   423.000000
41517         1208             0  Shallow Default  5.63   50.40   485.000000
9500           SLO             0  Shallow Default  5.90   11.20   821.321471
12648          BNV             0  Shallow Default  6.87   28.44   744.000000
39959         BOTT             0  Shallow Default  5.40  158.20   934.275262
9354          CIMA             0  Shallow Default  5.40   64.70   824.855804
19610         SGMA             0  Shallow Default  5.16   54.70   877.753740
7367          CIMA             0  Shallow Default  6.00   60.51   824.855804
31233         CIMA             0  Shallow Default  6.50   57.81   824.855804
21937         PSRA             0  Shallow Default  5.20  223.80   502.224366
16183          MDT             0  Shallow Default  6.10   78.70   769.109673
14018         RM13             0  Shallow Default  5.54   12.29   792.446158

       ... ims_scaled                                                    \
       ...  SA(0.311)   SA(0.4) SA(0.514) SA(0.662) SA(0.851) SA(1.095)
14086  ...   0.138793  0.069807  0.081364  0.046294  0.052731  0.033719
28372  ...   0.016854  0.016756  0.017061  0.017345  0.021841  0.022132
34129  ...   0.051180  0.047275  0.027352  0.026095  0.023941  0.022072
41077  ...   0.039133  0.038691  0.040034  0.051435  0.029448  0.026541
35080  ...   0.030578  0.045099  0.033514  0.021267  0.018814  0.023675
13587  ...   0.045870  0.037651  0.034482  0.034693  0.031332  0.025909
30415  ...   0.083303  0.091203  0.061266  0.054186  0.044217  0.030354
18373  ...   0.057386  0.041903  0.046926  0.042644  0.033284  0.029123
20168  ...   0.060142  0.063764  0.049104  0.044306  0.033062  0.028069
16167  ...   0.023608  0.025866  0.026397  0.026533  0.020458  0.020600
31188  ...   0.039889  0.043975  0.041049  0.023141  0.019031  0.022238
20226  ...   0.038941  0.034474  0.037309  0.034458  0.022090  0.027223
28241  ...   0.070662  0.057282  0.051867  0.044675  0.023330  0.020033
30388  ...   0.117479  0.099241  0.069295  0.036925  0.031495  0.022928
5649   ...   0.164856  0.127425  0.081070  0.060793  0.044168  0.033812
28294  ...   0.020733  0.022260  0.019951  0.026834  0.026789  0.022957
6553   ...   0.018880  0.017697  0.029431  0.035461  0.032765  0.035923
30381  ...   0.052538  0.040361  0.038450  0.033503  0.033565  0.035237
9296   ...   0.060392  0.061145  0.058761  0.061993  0.062108  0.048214
41517  ...   0.120676  0.074216  0.061430  0.061886  0.041746  0.027321
9500   ...   0.066143  0.077669  0.046780  0.042117  0.030453  0.027797
12648  ...   0.026396  0.021373  0.020413  0.017251  0.024327  0.029779
39959  ...   0.028196  0.026444  0.023320  0.022280  0.024990  0.029389
9354   ...   0.025884  0.022170  0.023114  0.029243  0.023398  0.025042
19610  ...   0.046953  0.045631  0.038041  0.039080  0.023397  0.017927
7367   ...   0.022972  0.021317  0.016969  0.021632  0.022436  0.019714
31233  ...   0.030280  0.024266  0.025865  0.025011  0.022373  0.024171
21937  ...   0.058472  0.042462  0.027627  0.028141  0.019626  0.015151
16183  ...   0.043005  0.046439  0.047130  0.057500  0.040277  0.032194
14018  ...   0.260235  0.130868  0.145245  0.087668  0.040098  0.021631


      SA(1.409) SA(1.812) SA(2.332)   SA(3.0)
14086  0.025226  0.010786  0.007120  0.003373
28372  0.023733  0.026739  0.018610  0.020779
34129  0.017840  0.015600  0.014811  0.012479
41077  0.029395  0.021968  0.009261  0.009184
35080  0.021591  0.021275  0.017688  0.011116
13587  0.019354  0.015126  0.012025  0.008809
30415  0.014185  0.012846  0.010555  0.007651
18373  0.026178  0.014816  0.010390  0.010947
20168  0.018176  0.015188  0.013129  0.006491
16167  0.030498  0.024206  0.016757  0.012538
31188  0.020676  0.021453  0.014425  0.010817
20226  0.026154  0.021729  0.012621  0.008201
28241  0.016206  0.015160  0.009953  0.009595
30388  0.018418  0.011798  0.008057  0.008761
5649   0.015418  0.008034  0.007288  0.004689
28294  0.023468  0.016751  0.017428  0.020653
6553   0.025600  0.021387  0.015695  0.007231
30381  0.017275  0.014587  0.011124  0.007587
9296   0.030421  0.016142  0.007704  0.003700
41517  0.022035  0.011104  0.009030  0.005114
9500   0.027014  0.015040  0.008560  0.007282
12648  0.024454  0.022845  0.018839  0.009416
39959  0.029543  0.022730  0.016365  0.008724
9354   0.019821  0.017483  0.011218  0.012431
19610  0.017342  0.016426  0.014215  0.012318
7367   0.031594  0.025307  0.017350  0.012668
31233  0.020473  0.021876  0.015619  0.015012
21937  0.013344  0.022250  0.013986  0.015267
16183  0.023739  0.011950  0.011987  0.008190
14018  0.013799  0.008845  0.005495  0.003312

[30 rows x 59 columns]

In [66]:
new_prelim_03[key_1]["recs"].index

Index([13744, 27563, 33165, 39994, 34105, 13247, 29603, 17978, 19717, 15795,
       30373, 19775, 27432, 29576,  5506, 27485,  6396, 29569,  9118, 40422,
        9321, 12346, 38910,  9176, 19182,  7191, 30418, 21272, 15811, 13676],
      dtype='int64')

In [65]:
new_prelim_03[key_1]["recs"]

      metadata                                                       \
         index database               event_id           event_time
13744    15878      ESM           IT-2009-0121  2009-04-09 00:52:59
27563     8491      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
33165    14951      ESM           IT-2002-0045  2002-10-31 10:33:00
39994    21995      ESM           TK-1999-0077  1999-08-17 00:01:38
34105    15908      ESM           IT-2009-0121  2009-04-09 00:52:59
13247    15376      ESM           IT-2008-0004  2008-12-23 15:24:21
29603    10607      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
17978    20201      ESM           IT-2012-0061  2012-10-25 23:05:24
19717    22049      ESM           TK-1999-0294  1999-09-13 11:55:27
15795    17973      ESM           IT-2012-0008  2012-05-20 02:03:50
30373    11393      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
19775    22108      ESM           TK-1999-0415  1999-11-12 16:57:19
27432     8358      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
29576    10580      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
5506      6203      ESM  EMSC-20150417_0000011  2015-04-17 02:05:39
27485     8413      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
6396      7379      ESM  EMSC-20151117_0000032  2015-11-17 08:33:43
29569    10573      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
9118     10452      ESM  EMSC-20161026_0000077  2016-10-26 17:10:36
40422    22440      ESM           TK-2005-0036  2005-03-23 21:44:52
9321     10657      ESM  EMSC-20161026_0000095  2016-10-26 19:18:06
12346    14427      ESM           IT-1980-0012  1980-11-23 18:34:53
38910    20827      ESM           IT-2013-0005  2013-06-21 10:33:56
9176     10510      ESM  EMSC-20161026_0000077  2016-10-26 17:10:36
19182    21474      ESM           IT-2013-0019  2013-12-29 17:08:43
7191      8450      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
30418    11441      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
21272     1087      ESM  EMSC-20120304_0000006  2012-03-04 03:31:09
15811    17989      ESM           IT-2012-0008  2012-05-20 02:03:50
13676    15810      ESM           IT-2009-0102  2009-04-07 17:47:37

                                                                              \
      station_code location_code              trt   mag     rjb         vs30
13744         MI02             0  Shallow Default  5.43   18.10   445.161197
27563         RNI2             0  Shallow Default  6.00  126.00   911.178534
33165          SCV             0  Shallow Default  5.71   41.49   495.270730
39994          ZYT             0  Shallow Default  7.40   64.68   543.605561
34105          SCP             0  Shallow Default  5.43  168.00   627.932386
13247        MFSFB             0  Shallow Default  5.46  245.89  1191.010983
29603          CTD             0  Shallow Default  5.90   52.29   407.000000
17978          VNN             0  Shallow Default  5.30   49.20   659.540631
19717         5902             0  Shallow Default  5.82  212.69   408.000000
15795          FIE             0  Shallow Default  6.10  109.81   765.918906
30373          SDM             0  Shallow Default  6.50   54.23   752.000000
19775          MSK             0  Shallow Default  7.10  160.12   573.862512
27432          GSA             0  Shallow Default  6.00   30.74   492.000000
29576          AQG             0  Shallow Default  5.90   54.37   696.000000
5506           ZKR             0  Shallow Default  5.20   46.90   705.516993
27485          SSO             0  Shallow Default  6.00  111.61   538.428785
6396           KBN             0  Shallow Default  5.10  219.90   742.000000
29569          ACC             0  Shallow Default  5.90   18.05   833.346095
9118           NOR             0  Shallow Default  5.40   10.20   423.000000
40422         1208             0  Shallow Default  5.63   50.40   485.000000
9321           SLO             0  Shallow Default  5.90   11.20   821.321471
12346          BNV             0  Shallow Default  6.87   28.44   744.000000
38910         BOTT             0  Shallow Default  5.40  158.20   934.275262
9176          CIMA             0  Shallow Default  5.40   64.70   824.855804
19182         SGMA             0  Shallow Default  5.16   54.70   877.753740
7191          CIMA             0  Shallow Default  6.00   60.51   824.855804
30418         CIMA             0  Shallow Default  6.50   57.81   824.855804
21272         PSRA             0  Shallow Default  5.20  223.80   502.224366
15811          MDT             0  Shallow Default  6.10   78.70   769.109673
13676         RM13             0  Shallow Default  5.54   12.29   792.446158

       ... ims_scaled                                                    \
       ...  SA(0.311)   SA(0.4) SA(0.514) SA(0.662) SA(0.851) SA(1.095)
13744  ...   0.138793  0.069807  0.081364  0.046294  0.052731  0.033719
27563  ...   0.016854  0.016756  0.017061  0.017345  0.021841  0.022132
33165  ...   0.051180  0.047275  0.027352  0.026095  0.023941  0.022072
39994  ...   0.039133  0.038691  0.040034  0.051435  0.029448  0.026541
34105  ...   0.030578  0.045099  0.033514  0.021267  0.018814  0.023675
13247  ...   0.045870  0.037651  0.034482  0.034693  0.031332  0.025909
29603  ...   0.083303  0.091203  0.061266  0.054186  0.044217  0.030354
17978  ...   0.057386  0.041903  0.046926  0.042644  0.033284  0.029123
19717  ...   0.060142  0.063764  0.049104  0.044306  0.033062  0.028069
15795  ...   0.023608  0.025866  0.026397  0.026533  0.020458  0.020600
30373  ...   0.039889  0.043975  0.041049  0.023141  0.019031  0.022238
19775  ...   0.038941  0.034474  0.037309  0.034458  0.022090  0.027223
27432  ...   0.070662  0.057282  0.051867  0.044675  0.023330  0.020033
29576  ...   0.117479  0.099241  0.069295  0.036925  0.031495  0.022928
5506   ...   0.164856  0.127425  0.081070  0.060793  0.044168  0.033812
27485  ...   0.020733  0.022260  0.019951  0.026834  0.026789  0.022957
6396   ...   0.018880  0.017697  0.029431  0.035461  0.032765  0.035923
29569  ...   0.052538  0.040361  0.038450  0.033503  0.033565  0.035237
9118   ...   0.060392  0.061145  0.058761  0.061993  0.062108  0.048214
40422  ...   0.120676  0.074216  0.061430  0.061886  0.041746  0.027321
9321   ...   0.066143  0.077669  0.046780  0.042117  0.030453  0.027797
12346  ...   0.026396  0.021373  0.020413  0.017251  0.024327  0.029779
38910  ...   0.028196  0.026444  0.023320  0.022280  0.024990  0.029389
9176   ...   0.025884  0.022170  0.023114  0.029243  0.023398  0.025042
19182  ...   0.046953  0.045631  0.038041  0.039080  0.023397  0.017927
7191   ...   0.022972  0.021317  0.016969  0.021632  0.022436  0.019714
30418  ...   0.030280  0.024266  0.025865  0.025011  0.022373  0.024171
21272  ...   0.058472  0.042462  0.027627  0.028141  0.019626  0.015151
15811  ...   0.043005  0.046439  0.047130  0.057500  0.040277  0.032194
13676  ...   0.260235  0.130868  0.145245  0.087668  0.040098  0.021631


      SA(1.409) SA(1.812) SA(2.332)   SA(3.0)
13744  0.025226  0.010786  0.007120  0.003373
27563  0.023733  0.026739  0.018610  0.020779
33165  0.017840  0.015600  0.014811  0.012479
39994  0.029395  0.021968  0.009261  0.009184
34105  0.021591  0.021275  0.017688  0.011116
13247  0.019354  0.015126  0.012025  0.008809
29603  0.014185  0.012846  0.010555  0.007651
17978  0.026178  0.014816  0.010390  0.010947
19717  0.018176  0.015188  0.013129  0.006491
15795  0.030498  0.024206  0.016757  0.012538
30373  0.020676  0.021453  0.014425  0.010817
19775  0.026154  0.021729  0.012621  0.008201
27432  0.016206  0.015160  0.009953  0.009595
29576  0.018418  0.011798  0.008057  0.008761
5506   0.015418  0.008034  0.007288  0.004689
27485  0.023468  0.016751  0.017428  0.020653
6396   0.025600  0.021387  0.015695  0.007231
29569  0.017275  0.014587  0.011124  0.007587
9118   0.030421  0.016142  0.007704  0.003700
40422  0.022035  0.011104  0.009030  0.005114
9321   0.027014  0.015040  0.008560  0.007282
12346  0.024454  0.022845  0.018839  0.009416
38910  0.029543  0.022730  0.016365  0.008724
9176   0.019821  0.017483  0.011218  0.012431
19182  0.017342  0.016426  0.014215  0.012318
7191   0.031594  0.025307  0.017350  0.012668
30418  0.020473  0.021876  0.015619  0.015012
21272  0.013344  0.022250  0.013986  0.015267
15811  0.023739  0.011950  0.011987  0.008190
13676  0.013799  0.008845  0.005495  0.003312

[30 rows x 59 columns]

In [95]:
def compare_df_ignore_index(
    df1, df2) -> bool:
    # Handle cases where one or both DataFrames are None
    if df1 is None and df2 is None:
        return True
    if df1 is None or df2 is None:
        return False

    # Reset index and compare values
    df1_reset = df1.reset_index(drop=True)
    df2_reset = df2.reset_index(drop=True)

    return df1_reset.equals(df2_reset)

In [76]:
old_prelim_03.keys() == new_prelim_03.keys()

True

In [96]:
different_gms_03 = []
for k in old_prelim_03.keys():

    if old_prelim_03[k] is None or new_prelim_03[k] is None:
        different_gms_03.append(k)
    
    elif not compare_df_ignore_index(old_prelim_03[k]["recs"], new_prelim_03[k]["recs"]):
        different_gms_03.append(k)

print(different_gms_03)

different_gms_06 = []
for k in old_prelim_06.keys():
    if old_prelim_06[k] is None or new_prelim_06[k] is None:
        different_gms_06.append(k)
    
    elif not compare_df_ignore_index(old_prelim_06[k]["recs"], new_prelim_06[k]["recs"]):
        different_gms_06.append(k)

print(different_gms_06)

[(0, np.float64(0.0001)), (2, np.float64(0.0001)), (3, np.float64(0.004988)), (5, np.float64(0.000201)), (6, np.float64(0.000404)), (6, np.float64(0.000201)), (6, np.float64(0.0001)), (7, np.float64(0.001)), (7, np.float64(0.000404)), (7, np.float64(0.000201)), (7, np.float64(0.0001)), (8, np.float64(0.000201)), (8, np.float64(0.0001)), (9, np.float64(0.0001)), (10, np.float64(0.000404)), (10, np.float64(0.000201)), (10, np.float64(0.0001)), (12, np.float64(0.000404)), (14, np.float64(0.000201)), (14, np.float64(0.0001)), (15, np.float64(0.000404)), (15, np.float64(0.0001)), (16, np.float64(0.001)), (17, np.float64(0.000404)), (18, np.float64(0.0001)), (19, np.float64(0.004988)), (20, np.float64(0.001)), (20, np.float64(0.000404)), (20, np.float64(0.000201)), (20, np.float64(0.0001)), (21, np.float64(0.004988)), (21, np.float64(0.000404)), (21, np.float64(0.000201)), (21, np.float64(0.0001)), (25, np.float64(0.000201)), (25, np.float64(0.0001)), (26, np.float64(0.002103)), (26, np.float64(0.000201)), (26, np.float64(0.0001)), (29, np.float64(0.002103)), (29, np.float64(0.0001)), (30, np.float64(0.001)), (30, np.float64(0.000404)), (30, np.float64(0.000201)), (30, np.float64(0.0001)), (32, np.float64(0.000404)), (32, np.float64(0.000201)), (32, np.float64(0.0001)), (33, np.float64(0.004988)), (33, np.float64(0.002103)), (33, np.float64(0.001)), (33, np.float64(0.000404)), (33, np.float64(0.000201)), (33, np.float64(0.0001)), (34, np.float64(0.002103)), (34, np.float64(0.001)), (34, np.float64(0.000404)), (34, np.float64(0.000201)), (34, np.float64(0.0001)), (35, np.float64(0.000404)), (35, np.float64(0.000201)), (35, np.float64(0.0001)), (36, np.float64(0.002103)), (36, np.float64(0.001)), (36, np.float64(0.000404)), (36, np.float64(0.000201)), (36, np.float64(0.0001)), (37, np.float64(0.001)), (37, np.float64(0.000201)), (37, np.float64(0.0001)), (39, np.float64(0.000404)), (39, np.float64(0.0001)), (40, np.float64(0.002103)), (40, np.float64(0.001)), (40, np.float64(0.000201)), (40, np.float64(0.0001)), (41, np.float64(0.000404)), (41, np.float64(0.000201)), (41, np.float64(0.0001)), (42, np.float64(0.002103)), (42, np.float64(0.001)), (42, np.float64(0.000404)), (43, np.float64(0.000201)), (43, np.float64(0.0001)), (44, np.float64(0.002103)), (44, np.float64(0.001)), (44, np.float64(0.0001)), (45, np.float64(0.002103)), (45, np.float64(0.001)), (45, np.float64(0.000404)), (45, np.float64(0.000201)), (45, np.float64(0.0001)), (46, np.float64(0.000404)), (46, np.float64(0.000201)), (46, np.float64(0.0001)), (47, np.float64(0.001)), (47, np.float64(0.000404)), (47, np.float64(0.000201)), (47, np.float64(0.0001)), (48, np.float64(0.001)), (48, np.float64(0.000201)), (48, np.float64(0.0001)), (50, np.float64(0.004988)), (50, np.float64(0.000201)), (51, np.float64(0.001)), (51, np.float64(0.000201)), (51, np.float64(0.0001)), (53, np.float64(0.001)), (53, np.float64(0.000404)), (53, np.float64(0.000201)), (53, np.float64(0.0001)), (54, np.float64(0.004988)), (54, np.float64(0.002103)), (54, np.float64(0.001)), (54, np.float64(0.000404)), (54, np.float64(0.000201)), (54, np.float64(0.0001))]
[(30, np.float64(0.000201)), (30, np.float64(0.0001))]

In [81]:
k1 = different_gms_03[0]

In [97]:
old_prelim_03[k1]["recs"]

       metadata                                                       \
          index database               event_id           event_time
31173     11377      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
34939     15767      ESM           IT-2009-0102  2009-04-07 17:47:37
40965     21883      ESM           TK-1983-0001  1983-07-05 12:01:27
19987     21865      ESM           SI-1998-0010  1998-04-12 10:55:31
12305     14012      ESM           GR-1999-0001  1999-09-07 11:56:49
12046     13719      ESM           GR-1983-0001  1983-01-17 12:41:30
12293     14000      ESM           GR-1997-0019  1997-11-18 13:07:38
33216     13953      ESM           GR-1995-0047  1995-06-15 00:15:47
7285       8366      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
28352      8471      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
10311     11484      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
20499     22384      ESM           TK-2004-0071  2004-08-04 03:01:05
40925     21832      ESM           ME-1979-0012  1979-05-24 17:23:17
31281     11490      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
28229      8346      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
12750     14536      ESM           IT-1984-0004  1984-05-07 17:49:43
33009     13718      ESM           GR-1983-0001  1983-01-17 12:41:30
28320      8439      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
14303     16095      ESM           IT-2009-0174  2009-04-13 21:14:24
16661     18472      ESM           IT-2012-0010  2012-05-29 10:55:56
35059     15887      ESM           IT-2009-0121  2009-04-09 00:52:59
37723     18570      ESM           IT-2012-0011  2012-05-29 07:00:02
81300   7006728   NGASub                7000049  YYYY-MM-DD HH:MM:00
80897   7006325   NGASub                7000049  YYYY-MM-DD HH:MM:00
42477   1000740   NGASub                1000050  YYYY-MM-DD HH:MM:00
123623  7004722   NGASub                7000044  YYYY-MM-DD HH:MM:00
126642  7007993   NGASub                7000057  YYYY-MM-DD HH:MM:00
46757   3001440   NGASub                3000177  YYYY-MM-DD HH:MM:00
54511   4018131   NGASub                4000040  YYYY-MM-DD HH:MM:00
117210  6001863   NGASub                6000331  YYYY-MM-DD HH:MM:00

                                                                           \
       station_code location_code                   trt   mag         rjb
31173           NOR             0       Shallow Default  6.50    3.140000
34939           AQV             0       Shallow Default  5.54   10.800000
40965          1012             0       Shallow Default  6.11   55.400000
19987          ILBA             0       Shallow Default  5.35   87.010000
12305          ATH4             0       Shallow Default  5.90   14.040000
12046          ARG1             0       Shallow Default  6.88   24.300000
12293          KYP1             0       Shallow Default  6.60   98.500000
33216          PYR1             0       Shallow Default  6.49   98.130000
7285            MNF             0       Shallow Default  6.00   20.370000
28352          MMUR             0       Shallow Default  6.00   65.050000
10311         T1201             0       Shallow Default  6.50    6.300000
20499          4802             0       Shallow Default  5.50   36.500000
40925          TIVA             0       Shallow Default  5.90   19.230000
31281         T1216             0       Shallow Default  6.50    3.060000
28229           FMG             0       Shallow Default  6.00   40.720000
12750          LPD1             0       Shallow Default  5.87   35.530000
33009          AGR1             0       Shallow Default  6.88  118.800000
28320          ATLO             0       Shallow Default  6.00   76.980000
14303           AMT             0       Shallow Default  5.03   16.700000
16661         MIR06             0       Shallow Default  5.48   18.040000
35059           AQV             0       Shallow Default  5.43   12.400000
37723          FIN0             0       Shallow Default  5.87    8.150000
81300       7000619             0     Subduction Inslab  6.94  132.435150
80897       7000054             0     Subduction Inslab  6.94   93.663612
42477       1000002             0  Subduction Interface  6.12   65.384462
123623      7000355             0  Subduction Interface  7.12   62.462819
126642      7000498             0  Subduction Interface  6.36   50.516698
46757       3000417             0  Subduction Interface  7.38  111.935814
54511       4001181             0  Subduction Interface  6.22  112.043140
117210      6000298             0  Subduction Interface  7.22  124.179613

                     ... ims_scaled                                          \
               vs30  ...  SA(0.311)   SA(0.4) SA(0.514) SA(0.662) SA(0.851)
31173    423.000000  ...   0.190584  0.163479  0.218427  0.201653  0.226088
34939    474.000000  ...   1.348536  1.031010  0.602752  0.350709  0.179427
40965    520.000000  ...   0.529694  0.381548  0.299243  0.247448  0.252496
19987    440.004870  ...   0.107513  0.092104  0.105245  0.108677  0.109855
12305   1020.000000  ...   0.374434  0.280653  0.355838  0.257825  0.199548
12046    442.000000  ...   0.796973  0.838951  0.671061  0.407601  0.198507
12293    641.000000  ...   0.588018  0.366689  0.333876  0.241673  0.172373
33216    473.000000  ...   0.365452  0.406987  0.378764  0.316593  0.227873
7285     980.827142  ...   0.436813  0.209532  0.207506  0.208082  0.228531
28352    509.465827  ...   0.361131  0.252946  0.218923  0.170412  0.141128
10311    425.634317  ...   0.453258  0.384845  0.424464  0.280409  0.252192
20499    746.000000  ...   0.577835  0.414773  0.322607  0.238810  0.146004
40925    525.838007  ...   0.732266  0.583328  0.487889  0.309822  0.206777
31281    804.820331  ...   0.906357  0.703137  0.497639  0.333683  0.175268
28229    790.000000  ...   0.219250  0.138521  0.159867  0.187722  0.244612
12750    786.603620  ...   0.693138  0.533523  0.293833  0.231271  0.187994
33009    466.396843  ...   0.237287  0.263027  0.258094  0.271729  0.313536
28320    511.624758  ...   0.206276  0.233594  0.218219  0.185167  0.129743
14303    670.000000  ...   1.109857  0.707908  0.639710  0.509388  0.224405
16661    418.430093  ...   0.431153  0.361421  0.243592  0.277703  0.146265
35059    474.000000  ...   0.749238  0.631712  0.473774  0.379313  0.250107
37723    437.099343  ...   0.556375  0.583737  0.481454  0.301318  0.151245
81300    726.568200  ...   0.316807  0.316110  0.242762  0.211413  0.166209
80897    597.847700  ...   0.701011  0.603807  0.506263  0.289107  0.218520
42477    635.000000  ...   0.309838  0.296419  0.257251  0.225857  0.145675
123623   544.464610  ...   0.291896  0.432413  0.281190  0.218137  0.248965
126642   543.675245  ...   0.105635  0.093333  0.113719  0.161808  0.173882
46757    517.000000  ...   0.289141  0.245834  0.220745  0.218202  0.253818
54511    566.700000  ...   0.327475  0.397725  0.320846  0.191466  0.195196
117210   517.000000  ...   0.178255  0.205317  0.280025  0.248918  0.163236


       SA(1.095) SA(1.409) SA(1.812) SA(2.332)   SA(3.0)
31173   0.237587  0.150861  0.089140  0.060080  0.044218
34939   0.119802  0.080886  0.053902  0.032202  0.018647
40965   0.242545  0.155712  0.078018  0.041784  0.022376
19987   0.126592  0.134824  0.131684  0.117487  0.124186
12305   0.156400  0.129968  0.076058  0.059877  0.028910
12046   0.154048  0.120580  0.072864  0.036164  0.022719
12293   0.201162  0.127652  0.056152  0.044527  0.030767
33216   0.167053  0.139395  0.080335  0.049276  0.028435
7285    0.214765  0.153774  0.088061  0.048865  0.022951
28352   0.131371  0.098680  0.059381  0.074812  0.064225
10311   0.173068  0.096815  0.053682  0.043008  0.052182
20499   0.142473  0.114104  0.071572  0.050739  0.024330
40925   0.139883  0.060860  0.045833  0.050907  0.029316
31281   0.139903  0.116748  0.053992  0.041541  0.027066
28229   0.157941  0.174056  0.079167  0.052848  0.082448
12750   0.147031  0.112401  0.076101  0.045544  0.028295
33009   0.162350  0.077824  0.097719  0.075668  0.040098
28320   0.119650  0.095192  0.083153  0.103672  0.056380
14303   0.131271  0.086323  0.058575  0.038623  0.016878
16661   0.109213  0.096289  0.073663  0.057192  0.032733
35059   0.160483  0.101939  0.065132  0.034463  0.020444
37723   0.125432  0.110398  0.071713  0.056522  0.029329
81300   0.155093  0.091371  0.072025  0.056561  0.058755
80897   0.123044  0.096250  0.066794  0.046981  0.040905
42477   0.126956  0.083957  0.088150  0.073414  0.049298
123623  0.175933  0.129579  0.086472  0.070021  0.041282
126642  0.154723  0.113210  0.096156  0.100766  0.062624
46757   0.177386  0.088086  0.066888  0.069566  0.037680
54511   0.203251  0.136393  0.073769  0.054159  0.043939
117210  0.229053  0.164324  0.124955  0.058094  0.043821

[30 rows x 59 columns]

In [98]:
new_prelim_03[k1]["recs"]

       metadata                                                       \
          index database               event_id           event_time
19497     21812      ESM           ME-1979-0003  1979-04-15 06:19:41
33964     15767      ESM           IT-2009-0102  2009-04-07 17:47:37
39884     21883      ESM           TK-1983-0001  1983-07-05 12:01:27
19540     21865      ESM           SI-1998-0010  1998-04-12 10:55:31
12019     14012      ESM           GR-1999-0001  1999-09-07 11:56:49
11766     13719      ESM           GR-1983-0001  1983-01-17 12:41:30
12007     14000      ESM           GR-1997-0019  1997-11-18 13:07:38
32298     13953      ESM           GR-1995-0047  1995-06-15 00:15:47
7109       8366      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
27543      8471      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
10129     11484      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
20037     22384      ESM           TK-2004-0071  2004-08-04 03:01:05
39848     21832      ESM           ME-1979-0012  1979-05-24 17:23:17
30466     11490      ESM  EMSC-20161030_0000029  2016-10-30 06:40:18
27420      8346      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
12436     14536      ESM           IT-1984-0004  1984-05-07 17:49:43
32096     13718      ESM           GR-1983-0001  1983-01-17 12:41:30
27511      8439      ESM  EMSC-20160824_0000006  2016-08-24 01:36:32
13960     16095      ESM           IT-2009-0174  2009-04-13 21:14:24
16285     18472      ESM           IT-2012-0010  2012-05-29 10:55:56
34084     15887      ESM           IT-2009-0121  2009-04-09 00:52:59
36714     18570      ESM           IT-2012-0011  2012-05-29 07:00:02
80035   7006728   NGASub                7000049  YYYY-MM-DD HH:MM:00
79632   7006325   NGASub                7000049  YYYY-MM-DD HH:MM:00
41212   1000740   NGASub                1000050  YYYY-MM-DD HH:MM:00
122358  7004722   NGASub                7000044  YYYY-MM-DD HH:MM:00
125377  7007993   NGASub                7000057  YYYY-MM-DD HH:MM:00
45492   3001440   NGASub                3000177  YYYY-MM-DD HH:MM:00
53246   4018131   NGASub                4000040  YYYY-MM-DD HH:MM:00
115945  6001863   NGASub                6000331  YYYY-MM-DD HH:MM:00

                                                                           \
       station_code location_code                   trt   mag         rjb
19497           ULA             0       Shallow Default  6.90    5.560000
33964           AQV             0       Shallow Default  5.54   10.800000
39884          1012             0       Shallow Default  6.11   55.400000
19540          ILBA             0       Shallow Default  5.35   87.010000
12019          ATH4             0       Shallow Default  5.90   14.040000
11766          ARG1             0       Shallow Default  6.88   24.300000
12007          KYP1             0       Shallow Default  6.60   98.500000
32298          PYR1             0       Shallow Default  6.49   98.130000
7109            MNF             0       Shallow Default  6.00   20.370000
27543          MMUR             0       Shallow Default  6.00   65.050000
10129         T1201             0       Shallow Default  6.50    6.300000
20037          4802             0       Shallow Default  5.50   36.500000
39848          TIVA             0       Shallow Default  5.90   19.230000
30466         T1216             0       Shallow Default  6.50    3.060000
27420           FMG             0       Shallow Default  6.00   40.720000
12436          LPD1             0       Shallow Default  5.87   35.530000
32096          AGR1             0       Shallow Default  6.88  118.800000
27511          ATLO             0       Shallow Default  6.00   76.980000
13960           AMT             0       Shallow Default  5.03   16.700000
16285         MIR06             0       Shallow Default  5.48   18.040000
34084           AQV             0       Shallow Default  5.43   12.400000
36714          FIN0             0       Shallow Default  5.87    8.150000
80035       7000619             0     Subduction Inslab  6.94  132.435150
79632       7000054             0     Subduction Inslab  6.94   93.663612
41212       1000002             0  Subduction Interface  6.12   65.384462
122358      7000355             0  Subduction Interface  7.12   62.462819
125377      7000498             0  Subduction Interface  6.36   50.516698
45492       3000417             0  Subduction Interface  7.38  111.935814
53246       4001181             0  Subduction Interface  6.22  112.043140
115945      6000298             0  Subduction Interface  7.22  124.179613

                     ... ims_scaled                                          \
               vs30  ...  SA(0.311)   SA(0.4) SA(0.514) SA(0.662) SA(0.851)
19497    804.947385  ...   0.238820  0.200004  0.237415  0.262552  0.190184
33964    474.000000  ...   1.348536  1.031010  0.602752  0.350709  0.179427
39884    520.000000  ...   0.529694  0.381548  0.299243  0.247448  0.252496
19540    440.004870  ...   0.107513  0.092104  0.105245  0.108677  0.109855
12019   1020.000000  ...   0.374434  0.280653  0.355838  0.257825  0.199548
11766    442.000000  ...   0.796973  0.838951  0.671061  0.407601  0.198507
12007    641.000000  ...   0.588018  0.366689  0.333876  0.241673  0.172373
32298    473.000000  ...   0.365452  0.406987  0.378764  0.316593  0.227873
7109     980.827142  ...   0.436813  0.209532  0.207506  0.208082  0.228531
27543    509.465827  ...   0.361131  0.252946  0.218923  0.170412  0.141128
10129    425.634317  ...   0.453258  0.384845  0.424464  0.280409  0.252192
20037    746.000000  ...   0.577835  0.414773  0.322607  0.238810  0.146004
39848    525.838007  ...   0.732266  0.583328  0.487889  0.309822  0.206777
30466    804.820331  ...   0.906357  0.703137  0.497639  0.333683  0.175268
27420    790.000000  ...   0.219250  0.138521  0.159867  0.187722  0.244612
12436    786.603620  ...   0.693138  0.533523  0.293833  0.231271  0.187994
32096    466.396843  ...   0.237287  0.263027  0.258094  0.271729  0.313536
27511    511.624758  ...   0.206276  0.233594  0.218219  0.185167  0.129743
13960    670.000000  ...   1.109857  0.707908  0.639710  0.509388  0.224405
16285    418.430093  ...   0.431153  0.361421  0.243592  0.277703  0.146265
34084    474.000000  ...   0.749238  0.631712  0.473774  0.379313  0.250107
36714    437.099343  ...   0.556375  0.583737  0.481454  0.301318  0.151245
80035    726.568200  ...   0.316807  0.316110  0.242762  0.211413  0.166209
79632    597.847700  ...   0.701011  0.603807  0.506263  0.289107  0.218520
41212    635.000000  ...   0.309838  0.296419  0.257251  0.225857  0.145675
122358   544.464610  ...   0.291896  0.432413  0.281190  0.218137  0.248965
125377   543.675245  ...   0.105635  0.093333  0.113719  0.161808  0.173882
45492    517.000000  ...   0.289141  0.245834  0.220745  0.218202  0.253818
53246    566.700000  ...   0.327475  0.397725  0.320846  0.191466  0.195196
115945   517.000000  ...   0.178255  0.205317  0.280025  0.248918  0.163236


       SA(1.095) SA(1.409) SA(1.812) SA(2.332)   SA(3.0)
19497   0.131658  0.145343  0.116837  0.067330  0.036152
33964   0.119802  0.080886  0.053902  0.032202  0.018647
39884   0.242545  0.155712  0.078018  0.041784  0.022376
19540   0.126592  0.134824  0.131684  0.117487  0.124186
12019   0.156400  0.129968  0.076058  0.059877  0.028910
11766   0.154048  0.120580  0.072864  0.036164  0.022719
12007   0.201162  0.127652  0.056152  0.044527  0.030767
32298   0.167053  0.139395  0.080335  0.049276  0.028435
7109    0.214765  0.153774  0.088061  0.048865  0.022951
27543   0.131371  0.098680  0.059381  0.074812  0.064225
10129   0.173068  0.096815  0.053682  0.043008  0.052182
20037   0.142473  0.114104  0.071572  0.050739  0.024330
39848   0.139883  0.060860  0.045833  0.050907  0.029316
30466   0.139903  0.116748  0.053992  0.041541  0.027066
27420   0.157941  0.174056  0.079167  0.052848  0.082448
12436   0.147031  0.112401  0.076101  0.045544  0.028295
32096   0.162350  0.077824  0.097719  0.075668  0.040098
27511   0.119650  0.095192  0.083153  0.103672  0.056380
13960   0.131271  0.086323  0.058575  0.038623  0.016878
16285   0.109213  0.096289  0.073663  0.057192  0.032733
34084   0.160483  0.101939  0.065132  0.034463  0.020444
36714   0.125432  0.110398  0.071713  0.056522  0.029329
80035   0.155093  0.091371  0.072025  0.056561  0.058755
79632   0.123044  0.096250  0.066794  0.046981  0.040905
41212   0.126956  0.083957  0.088150  0.073414  0.049298
122358  0.175933  0.129579  0.086472  0.070021  0.041282
125377  0.154723  0.113210  0.096156  0.100766  0.062624
45492   0.177386  0.088086  0.066888  0.069566  0.037680
53246   0.203251  0.136393  0.073769  0.054159  0.043939
115945  0.229053  0.164324  0.124955  0.058094  0.043821

[30 rows x 59 columns]

In [ ]:
np.allclose(old_prelim_03[k1]["sims"].to_numpy(), new_prelim_03[k1]["sims"].to_numpy())

True

In [101]:
old_prelim_03[k1].keys()

dict_keys(['sims', 'mu_cond_sims', 'sig_cond_sims', 'ctxs', 'eps', 'recs', 'ks_passed', 'ks_results', 'ks_failed_ims', 'ks_bounds', 'R-score', 'ecdfs', 'quantiles', 'cond_imt', 'cond_iml', 'filter_stats'])

In [ ]:
print(np.allclose(old_prelim_03[k1]["mu_cond_sims"], new_prelim_03[k1]["mu_cond_sims"]))
print(np.allclose(old_prelim_03[k1]["sig_cond_sims"], new_prelim_03[k1]["sig_cond_sims"]))
print(all(old_prelim_03[k1]["ctxs"] == new_prelim_03[k1]["ctxs"]))

True
True

In [106]:
old_prelim_03[k1]["filter_stats"]

{'m_bounds': (np.float64(4.977), np.float64(8.411)),
 'd_bounds': (np.float64(2.5), np.float64(143.405)),
 'vs30_bounds': (400.0, 1200.0),
 'sf_bounds': None,
 'usable_T_bound': 3,
 'N_recs': 130081,
 'N_recs|m': 87492,
 '% N_recs|m': 0.6725963053789562,
 'N_recs|m,d': 28220,
 '% N_recs|m,d': 0.21694175167780075,
 'N_recs|m,d,v': 15274,
 '% N_recs|m,d,v': 0.11741914653177636,
 'N_recs|m,d,v,t': 12248,
 '% N_recs|m,d,v,t': 0.09415671773740977,
 'N_recs|m,d,v,t,sf': 12248,
 '% N_recs|m,d,v,t,sf': 0.09415671773740977}

In [107]:
new_prelim_03[k1]["filter_stats"]

{'m_bounds': (np.float64(4.977), np.float64(8.411)),
 'd_bounds': (np.float64(2.5), np.float64(143.405)),
 'vs30_bounds': (400.0, 1200.0),
 'sf_bounds': None,
 'usable_T_bound': 3,
 'N_recs': 128816,
 'N_recs|m': 87012,
 '% N_recs|m': 0.675475096261334,
 'N_recs|m,d': 27912,
 '% N_recs|m,d': 0.2166811576201714,
 'N_recs|m,d,v': 15216,
 '% N_recs|m,d,v': 0.11812197242578562,
 'N_recs|m,d,v,t': 12226,
 '% N_recs|m,d,v,t': 0.0949105701155136,
 'N_recs|m,d,v,t,sf': 12226,
 '% N_recs|m,d,v,t,sf': 0.0949105701155136}

checking the database of gm records because there seems to be a descrepancy here...

In [108]:
import phd_project.scripts.WP1_ground_motion_set.manage_flatfiles as mf
from openquake.hazardlib.imt import PGA, SA, RSD595, AvgSA, IA, IMT

t_lower = 0.025     # lower SA period considered in selection
t_upper = 3         # upper SA period considered in selection
n_periods = 20      # number of periods to consider in selection

conditioning_imt: IMT = AvgSA([0,3]) 
nonSA_imts: list[IMT] = [AvgSA([0,3]), RSD595(), PGA()] 
sa_periods = np.round(np.geomspace(t_lower, t_upper, num=n_periods), 3)
SA_imts: list[IMT] = [SA(period) for period in sa_periods]
selection_imts: list[IMT] = nonSA_imts[1:] + SA_imts    # not AvgSA but the others (PGA and RSD595)
nonSA_imt_strs: list[str] = [im.string for im in nonSA_imts] # strings match the correlation matrix


# load the old preprocessed gm database
gm_database = pd.read_csv(Path(r"C:\Users\clemettn\Desktop\old_selection\ESM-NGAsub_combined.csv"), sep=",", low_memory=False, header=[0, 1])

# filter the gm_database so that only the selection and conditioning ims are present
old_gm_db = gm_database.copy()
updated_ims = mf.filter_gm_database_on_imts(
    old_gm_db["ims"], selection_imts + [conditioning_imt])
updated_ims.columns = pd.MultiIndex.from_product([['ims'], updated_ims.columns])
old_gm_db = pd.concat([old_gm_db.drop('ims', axis=1, level=0), updated_ims], axis=1)

# load the new preprocessed gm database
gm_database = pd.read_csv(Path(r"C:\Users\clemettn\Desktop\new_selection\ESM-NGAsub_combined.csv"), sep=",", low_memory=False, header=[0, 1])

# filter the gm_database so that only the selection and conditioning ims are present
new_gm_db = gm_database.copy()
updated_ims = mf.filter_gm_database_on_imts(
    new_gm_db["ims"], selection_imts + [conditioning_imt])
updated_ims.columns = pd.MultiIndex.from_product([['ims'], updated_ims.columns])
new_gm_db = pd.concat([new_gm_db.drop('ims', axis=1, level=0), updated_ims], axis=1)

In [111]:
print(len(old_gm_db))
print(len(new_gm_db))

130449
128816

check the hazard disaggregations

In [ ]:
with open(old_selection_fp / "06_gm_selection/AvgSA_03_prelim_selection.pickle", "rb") as file:
    old_prelim_03 = pickle.load(file)